name: satellite-ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-lightning
  - segmentation-models-pytorch
  - scikit-learn
  - rasterio
  - geopandas
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - opencv
  - albumentations
  - tqdm
  - scipy
  - pip
  - pip:
    - opencv-python